/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.ItemController;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.ArrayList;

/**
 *
 * @author JORGE MANCERA
 */
public class Items extends javax.swing.JDialog {

    /**
     * Creates new form Items
     */
    ItemController citem = new ItemController();
    public Items(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         this.getContentPane().setBackground(new java.awt.Color(188,200,214,255));
        citem.show(table);
        table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        table.setRowHeight(25);
        table.setShowVerticalLines(false);
        table.getTableHeader().setReorderingAllowed(false);
        table.setSelectionBackground(new java.awt.Color(52, 152, 219));
        table.setFont(new java.awt.Font("Sans Serif", 0, 16));
        table.getTableHeader().setFont(new java.awt.Font("Sans Serif", Font.PLAIN, 16));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txItem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SisVenPro 2.0 - [Articulos]");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 618, 230));

        jPanel1.setBackground(new java.awt.Color(217, 225, 230));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_binoculars_icon.png"))); // NOI18N
        jLabel1.setText("Buscar articulo");
        jLabel1.setToolTipText("");

        txItem.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txItemKeyReleased(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(36, 83, 148));
        jButton1.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/memo-edit-document.png"))); // NOI18N
        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txItem, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txItemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txItemKeyReleased
       String item=txItem.getText();
        citem.search(table, item);
    }//GEN-LAST:event_txItemKeyReleased

    private void tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyReleased
            char cKey = evt.getKeyChar();
                if (cKey == KeyEvent.VK_ENTER) {
                   int index = table.getSelectedRow();
                   ArrayList<Object> data = new ArrayList<>();
                 
                   data.add(table.getValueAt(index,1).toString());
                   data.add(table.getValueAt(index,2).toString());
                   data.add(table.getValueAt(index,3).toString());
                   data.add(table.getValueAt(index,0).toString());
                   citem.edit(data); 
                }
    }//GEN-LAST:event_tableKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         int index = table.getSelectedRow();
                   ArrayList<Object> data = new ArrayList<>();
                 
                   data.add(table.getValueAt(index,1).toString());
                   data.add(table.getValueAt(index,2).toString());
                   data.add(table.getValueAt(index,3).toString());
                   data.add(table.getValueAt(index,0).toString());
                   citem.edit(data); 
                   
                   citem.show(table);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txItem;
    // End of variables declaration//GEN-END:variables
}
